### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by aevyrie** [amPerl/egui-phosphor#1]
Could you please add a license file to this repo? It looks like MIT is specified in the `cargo.toml`.

FWIW, dual licensing as MIT + Apache 2.0 would provide the greatest ecosystem compatibility, if that is acceptable to you (see the egui repo for example: https://github.com/emilk/egui)

**Comment by amPerl** [comment]
Sounds good to me! Fixed in bad6ba90aa0837189096da6eeac51b9d1fd6a5c2

**Comment by aevyrie** [comment]
Thank you!
