### ISSUE TITLE
Centering in buttons

### ISSUE THREAD

**Issue by ZeWaka** [amPerl/egui-phosphor#5]
Hi,
I'm not sure if this is an egui-phosphor issue specifically, but when the icons are used within a button, they're not vertically centered/padded within by default. 
I'm not even sure this is fixable on this end, since it's just a font. Perhaps some guidance could be given in the readme or examples to solve this, however.

Example:
![image](https://github.com/amPerl/egui-phosphor/assets/4741640/5ec33bf9-caeb-4306-ae1d-f0ca04ce98df)

(Notice the padding on the top but not the bottom)

**Comment by amPerl** [comment]
hi! sorry for taking so long to get to this.

I'm unable to reproduce this issue on the `debug_alignment` example on this repo.
on this screenshot i've added two buttons to the demo, with nothing else changed compared to the labels:

![image](https://github.com/amPerl/egui-phosphor/assets/461652/deb70f00-95e6-431f-b52f-81c045d8ae3c)

are you sure there's nothing else in your project and its layout affecting either the size of those buttons or the font's baseline?
if so, could you try and create a minimal reproduction of the alignment failure on eframe? thanks!
