### ISSUE TITLE
Icons in thin module are misplaced

### ISSUE THREAD

**Issue by aspect** [amPerl/egui-phosphor#8]
It appears that ranges of icons in (at least) the `thin` module are misplaced in an "off by one" fashion.

If you use `LIST` you get `LIST_PLUS` and this affects others, but they seem to be in ranges, as `CLOUD_X` is fine.  However all `LIST_XXX` are affected, `CHECK_XXX` and there are a bunch more, unfortunately, I can't tell which ranges right now.  The shift seems to be specific to `thin` module but I could be wrong.  Perhaps making a small dump to examine or to re-examine the import process would help.

LMK if you need any help/feedback.  I am extensively using this right now in an Egui project.

**Comment by amPerl** [comment]
Hi and thanks for raising this. I know this is super old and I'm sorry. Since the fonts got updated with 0.6.0, is this still relevant?

**Comment by aspect** [comment]
I'll give this a try in the coming days and will report back.

**Comment by CtByte** [comment]
@amPerl Hi there, when checking out the latest version, `egui-phosphor = "0.7"`, at least the CPU icon seems wrong. I expected [this icon instead](https://phosphoricons.com/?q=%22cpu%22)

![image](https://github.com/user-attachments/assets/8eca5b3b-2853-418e-bb38-de6fa450e2a0)
![image](https://github.com/user-attachments/assets/7162b426-63eb-45a8-a90c-c81547fec330)

**Comment by amPerl** [comment]
thanks! looks like the built in egui fonts were taking priority here. could you update and check if 0.7.2 fixes it for you?

**Comment by CtByte** [comment]
@amPerl `CPU` is fixed in version `0.7.2`. Thank you so much for the quick response!

In case you wanted a confirmation on the original issue, I also tested the `LIST` and `LIST_PLUS` icons and they are also correct.

**Comment by bircni** [comment]
@CtByte does this still work with `0.7.3` for you?

**Comment by CtByte** [comment]
@bircni `egui_phosphor::regular::CPU` does seem to still work in `0.7.3`
![image](https://github.com/user-attachments/assets/a337b428-7e6b-41aa-846d-bc8460b7b089)

**Comment by bircni** [comment]
so this can be closed?

**Comment by CtByte** [comment]
My issue is solved, so if you are asking me, it can be. I am grateful for the quick help!
